<a href="https://colab.research.google.com/github/RV05/Spam-Detection/blob/main/spam_detection_Naive_Bayes_Classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [37]:
#Load the necessary python libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
plt.style.use('ggplot')

In [40]:
message = pd.read_csv('/content/drive/MyDrive/alma/spam.csv', encoding='latin-1')[['v1', 'v2']]
message.columns = ['label', 'message']
message.head()

label                                            message
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [41]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [ ]:
import string
from nltk.corpus import stopwords

In [42]:
def text_process(msg):
    nopunc =[char for char in msg if char not in string.punctuation]
    nopunc=''.join(nopunc)
    return ' '.join([word for word in nopunc.split() if word.lower() not in stopwords.words('english')])

In [43]:
message['tokenized_message'] = message['message'].apply(text_process)

In [44]:
message.head()

label  ...                                  tokenized_message
0   ham  ...  Go jurong point crazy Available bugis n great ...
1   ham  ...                            Ok lar Joking wif u oni
2  spam  ...  Free entry 2 wkly comp win FA Cup final tkts 2...
3   ham  ...                U dun say early hor U c already say
4   ham  ...        Nah dont think goes usf lives around though

[5 rows x 3 columns]

In [66]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(max_df = 0.9,min_df = 10)
X = vectorizer.fit_transform(message['tokenized_message'])

In [67]:
message.iloc[4065]['tokenized_message']

'Fyi Im gonna call sporadically starting like ltgt bc doin shit'

In [68]:
from sklearn.model_selection import train_test_split
msg_train,msg_test,label_train,label_test = train_test_split(message['tokenized_message'],message['label'],test_size=0.2)

In [69]:
msg_train.head()

340                              Ok thats great thanx lot
3177                                      K k watch films
1939    people dogging area Call 09090204448 join like...
4022                           Well Balls Time make calls
4266    SORRY IM STIL FUCKED LAST NITE WENT TOBED 430 ...
Name: tokenized_message, dtype: object

In [70]:
train_vectorized = vectorizer.transform(msg_train)
test_vectorized = vectorizer.transform(msg_test)

In [71]:
train_vectorized

<4457x872 sparse matrix of type '<class 'numpy.float64'>'
	with 24558 stored elements in Compressed Sparse Row format>

In [72]:
train_array= train_vectorized.toarray()
test_array = test_vectorized.toarray()

In [73]:
from sklearn.naive_bayes import GaussianNB
spam_detect_model = GaussianNB().fit(train_array,label_train)

In [74]:
train_preds = spam_detect_model.predict(train_array)
test_preds = spam_detect_model.predict(test_array)

In [75]:
from sklearn.metrics import classification_report,confusion_matrix

In [76]:
# Confusion matrices for train and test 

print(confusion_matrix(label_train,train_preds))
print(confusion_matrix(label_test,test_preds))

[[2976  889]
 [   0  592]]
[[735 225]
 [  8 147]]


In [77]:
# Print the classification report for train and test
print(classification_report(label_train,train_preds))
print("\n")
print(classification_report(label_test,test_preds))

              precision    recall  f1-score   support

         ham       1.00      0.77      0.87      3865
        spam       0.40      1.00      0.57       592

    accuracy                           0.80      4457
   macro avg       0.70      0.88      0.72      4457
weighted avg       0.92      0.80      0.83      4457



              precision    recall  f1-score   support

         ham       0.99      0.77      0.86       960
        spam       0.40      0.95      0.56       155

    accuracy                           0.79      1115
   macro avg       0.69      0.86      0.71      1115
weighted avg       0.91      0.79      0.82      1115



In [78]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(train_array,label_train)

In [79]:

train_preds = spam_detect_model.predict(train_array)
test_preds = spam_detect_model.predict(test_array)

In [80]:
print(confusion_matrix(label_train,train_preds))
print(confusion_matrix(label_test,test_preds))

[[3856    9]
 [  85  507]]
[[958   2]
 [ 18 137]]


In [81]:
print(classification_report(label_train,train_preds))
print("\n")
print(classification_report(label_test,test_preds))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      3865
        spam       0.98      0.86      0.92       592

    accuracy                           0.98      4457
   macro avg       0.98      0.93      0.95      4457
weighted avg       0.98      0.98      0.98      4457



              precision    recall  f1-score   support

         ham       0.98      1.00      0.99       960
        spam       0.99      0.88      0.93       155

    accuracy                           0.98      1115
   macro avg       0.98      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [85]:
 from sklearn.naive_bayes import BernoulliNB
spam_detect_model = BernoulliNB().fit(train_array,label_train)

In [86]:
train_preds = spam_detect_model.predict(train_array)
test_preds = spam_detect_model.predict(test_array)

In [87]:
print(confusion_matrix(label_train,train_preds))
print(confusion_matrix(label_test,test_preds))

[[3859    6]
 [  71  521]]
[[957   3]
 [ 14 141]]


In [88]:
print(classification_report(label_train,train_preds))
print("\n")
print(classification_report(label_test,test_preds))


              precision    recall  f1-score   support

         ham       0.98      1.00      0.99      3865
        spam       0.99      0.88      0.93       592

    accuracy                           0.98      4457
   macro avg       0.99      0.94      0.96      4457
weighted avg       0.98      0.98      0.98      4457



              precision    recall  f1-score   support

         ham       0.99      1.00      0.99       960
        spam       0.98      0.91      0.94       155

    accuracy                           0.98      1115
   macro avg       0.98      0.95      0.97      1115
weighted avg       0.98      0.98      0.98      1115

